name: Run tests
on:
  push:
    branches: [main, v0]
    tags-ignore: ['**']
    paths: ['src/**/*.rs']
  pull_request:
    tags-ignore: ['**']
    paths: ['src/**/*.rs']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
      - name: Test documentation
        run: |
          export RUSTDOCFLAGS="-D warnings"
          cargo doc --all-features --no-deps
      - name: Run linter
        run: |
          export RUSTFLAGS="-D warnings"
          cargo clippy --features autoposter,serenity
          cargo clippy --features autoposter,serenity-cached
          cargo clippy --features autoposter,twilight
          cargo clippy --features autoposter,twilight-cached
          cargo clippy --features webhook
          cargo clippy --features rocket
          cargo clippy --features axum
          cargo clippy --features warp
          cargo clippy --features actix-web